# Generated by Django 2.1.15 on 2020-04-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp_avans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='months',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=120)),
                ('rus', models.CharField(max_length=120)),
            ],
        ),
    ]
