# Generated by Django 2.1.15 on 2020-05-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pur_date', models.DateField()),
                ('inv', models.IntegerField()),
                ('bal_price', models.FloatField()),
                ('type_id', models.IntegerField()),
                ('amort_month', models.FloatField()),
                ('date_vvod', models.DateField()),
                ('izm', models.IntegerField()),
                ('dop_month', models.IntegerField()),
                ('emp_id', models.IntegerField()),
                ('kol_month', models.IntegerField()),
                ('amort_sum', models.FloatField()),
                ('amort_sum_month', models.FloatField()),
                ('perehod_m_s', models.FloatField()),
                ('company_id', models.IntegerField()),
                ('branch_id', models.IntegerField()),
            ],
        ),
    ]
