# Generated by Django 2.1.15 on 2020-05-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0002_auto_20200525_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='date_vvod',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='pur_date',
            field=models.DateField(null=True),
        ),
    ]
