# Generated by Django 2.1.15 on 2020-05-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0004_auto_20200526_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='amort_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oborud', models.IntegerField()),
                ('date_amort', models.DateField()),
                ('amort_sum_month', models.FloatField()),
                ('ost_sum', models.FloatField()),
                ('amort_sum', models.FloatField()),
                ('norm_months', models.IntegerField()),
                ('bal_price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='main_t',
            name='id_oborud',
            field=models.IntegerField(null=True),
        ),
    ]
