# Generated by Django 3.0.6 on 2020-07-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0005_auto_20200531_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='change_bal_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oborud', models.IntegerField()),
                ('change_id', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('summ', models.FloatField()),
                ('date', models.DateField()),
                ('summ_before', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='type_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('type_id', models.IntegerField()),
                ('srok_months', models.IntegerField()),
            ],
        ),
    ]
