# Generated by Django 3.0.6 on 2020-07-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0006_change_bal_price_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_spisan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=120)),
                ('type_spisan_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='main_t',
            name='date_spisan',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='main_t',
            name='spisan_comm',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='main_t',
            name='type_spisan',
            field=models.IntegerField(null=True),
        ),
    ]
