# Generated by Django 3.0.6 on 2020-07-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0007_auto_20200720_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
