# Generated by Django 3.0.6 on 2020-08-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0009_remove_company_id_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='amort_t',
            name='ostatok_sroka',
            field=models.IntegerField(null=True),
        ),
    ]
