# Generated by Django 3.0.6 on 2020-09-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0011_branch_id_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_id', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='emp_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('depart_id', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='employee_id',
        ),
    ]
