# Generated by Django 3.0.6 on 2020-09-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0012_auto_20200924_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emp_id',
        ),
    ]
