# Generated by Django 3.0.6 on 2020-09-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0015_auto_20200924_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_id',
            name='lastname',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='employee_id',
            name='surname',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
