# Generated by Django 3.0.6 on 2020-09-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0016_auto_20200924_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_id',
            name='depart_id',
            field=models.IntegerField(null=True),
        ),
    ]
