# Generated by Django 3.0.6 on 2020-09-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0017_auto_20200924_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_id',
            name='lastname',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='employee_id',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='employee_id',
            name='surname',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
