# Generated by Django 3.0.6 on 2020-10-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0018_auto_20200924_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_t',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main_t',
            name='dop_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main_t',
            name='izm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main_t',
            name='kol_month',
            field=models.IntegerField(null=True),
        ),
    ]
