# Generated by Django 3.0.6 on 2020-10-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0019_auto_20201002_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_t',
            name='perehod_m_s',
            field=models.FloatField(null=True),
        ),
    ]
