# Generated by Django 3.1.3 on 2020-11-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0020_auto_20201002_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_t',
            name='change_sum',
            field=models.IntegerField(null=True),
        ),
    ]
