# Generated by Django 3.1.3 on 2020-11-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0021_main_t_change_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_t',
            name='change_sum',
        ),
    ]
