# Generated by Django 3.1.3 on 2020-12-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0022_remove_main_t_change_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_t',
            name='emp_id',
            field=models.IntegerField(null=True),
        ),
    ]
