# Generated by Django 3.1.3 on 2020-12-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0023_auto_20201210_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_id',
            name='active',
            field=models.IntegerField(null=True),
        ),
    ]
