# Generated by Django 3.1.3 on 2021-01-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0024_employee_id_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='history_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oborud', models.IntegerField()),
                ('inv', models.IntegerField()),
                ('date_moving', models.DateField()),
                ('ex_emp', models.IntegerField()),
                ('new_emp', models.IntegerField()),
            ],
        ),
    ]
