# Generated by Django 3.1.3 on 2021-01-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0025_history_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_item',
            name='name_item',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
