# Generated by Django 3.1.3 on 2021-01-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0026_history_item_name_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='history_item',
        ),
    ]
