# Generated by Django 3.1.3 on 2021-01-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0028_history_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_item',
            name='username',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
