# Generated by Django 3.1.3 on 2021-11-02 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_db', '0031_depart_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_id',
            name='branch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload_db.branch_id'),
        ),
    ]
